addr: ":8080"
dataDir: "/data/sites"
baseDomain: "kanban.yolo.scapegoat.dev"
dev: false
sites:
  - name: trail
    scripts:
      - /app/sites/trail/scripts
  - name: editorial
    scripts:
      - /app/sites/editorial/scripts
  - name: crm
    scripts:
      - /app/sites/crm/scripts
  - name: pizza
    scripts:
      - /app/sites/pizza/scripts
